/* SPDX-License-Identifier: MIT
 * Copyright (c) 2026 Chris Dragan
 */

#pragma once

#include "static_assert.h"

#include <stdint.h>

/* The macOS LC_MAIN entry point receives argc/argv/envp/apple in x0-x3.
 * The loader forwards all four values to the original program's entry
 * point, so that its main() sees its arguments untouched.
 */
typedef int (* MACHO_ENTRY_POINT)(int argc, char **argv, char **envp, char **apple);

/* One rebase for a pointer living in the __DATA segment.  The loader applies it
 * by adding the image base (address where the executable was loaded) to
 * target_offs and storing the result in the pointer at image_base + slot_offs:
 *     *(uintptr_t *)(image_base + slot_offs) = image_base + target_offs;
 */
typedef struct {
    uint64_t slot_offs;
    uint64_t target_offs;
} MACHO_DATA_REBASE;

/* The combined arith payload is stored in up to this many disjoint file
 * ranges -- the unused alignment gap before the loader, the __TEXT
 * tail, and the __DATA_CONST page padding -- so no space is wasted.  The
 * loader concatenates the ranges in order to recover the payload.
 */
#define MACHO_MAX_PAYLOAD_RANGES 4U

/* This struct lives in __TEXT,__layout section of the loader.
 * It is filled by the compressor.  The loader code reaches it via a
 * PC-relative ADRP+ADD generated by the compiler for accesses to the
 * `macho_live_layout` global.
 *
 * All pointer-like fields are stored as offsets from the runtime image
 * base, NOT absolute addresses.  Mach-O PIE / arm64 ASLR slides the image
 * by a random multiple of the page size; absolute addresses written by
 * the compressor would not be rebased by dyld (we are not adding chained
 * fixups for our layout), so the loader computes the slide itself by
 * subtracting `layout_image_offs` from the runtime address of this
 * struct.
 */
typedef struct {
    uint64_t layout_image_offs;
    uint64_t decomp_base_offs;     /* __UNPACK base (decompressed __TEXT dest)   */
    uint64_t lz77_data_offs;       /* __SCRATCH: combined LZ bytes (arith output) */
    uint64_t entry_point_offs;     /* original program entry                     */
    uint64_t data_raw_offs;        /* __SCRATCH: combined raw [__TEXT][rebases][__data] (LZ output) */
    uint64_t data_dest_offs;       /* __DATA segment base                        */
    uint64_t payload_range_offs[MACHO_MAX_PAYLOAD_RANGES]; /* combined payload pieces */
    uint32_t payload_range_size[MACHO_MAX_PAYLOAD_RANGES];
    uint32_t payload_range_count;
    uint32_t decomp_size;          /* decompressed __TEXT size (== __UNPACK vmsize); also the split point between __TEXT and __DATA in the combined raw */
    uint32_t lz77_data_size;       /* combined LZ byte count (arith output size) */
    uint32_t data_content_size;    /* __data bytes to place (0 => no __DATA path)*/
    uint32_t data_rebase_count;    /* number of MACHO_DATA_REBASE entries        */
    uint32_t reserved;             /* pad to an 8-byte multiple; kept zero       */
} MACHO_LIVE_LAYOUT;

STATIC_ASSERT(sizeof(MACHO_LIVE_LAYOUT) == 120,
              "MACHO_LIVE_LAYOUT size changed; keep exe_macho.c in sync");

/* Compute the runtime image base from the runtime address of the layout
 * struct.  Used by the loader only.
 */
static inline uintptr_t macho_live_image_base(const MACHO_LIVE_LAYOUT *layout)
{
    return (uintptr_t)layout - (uintptr_t)layout->layout_image_offs;
}
